// <auto-generated />
using System;
using Alquileres.Infrastructuree.EntityFrameworkDatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alquileres.Infrastructuree.Migrations
{
    [DbContext(typeof(AlquileresDBContext))]
    [Migration("20211227171545_Creacion-Base-Datos")]
    partial class CreacionBaseDatos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Alquileres.Domain.Owner", b =>
                {
                    b.Property<string>("IdOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdOwner");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Alquileres.Domain.Property", b =>
                {
                    b.Property<string>("IdProperty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeInternal")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdProperty");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("Alquileres.Domain.PropertyImage", b =>
                {
                    b.Property<string>("IdPropertyImage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdProperty")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPropertyImage");

                    b.ToTable("PropertyImage");
                });

            modelBuilder.Entity("Alquileres.Domain.PropertyTrace", b =>
                {
                    b.Property<string>("IdPropertyTrace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdProperty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("IdPropertyTrace");

                    b.ToTable("PropertyTrace");
                });
#pragma warning restore 612, 618
        }
    }
}
