// <auto-generated />
using System;
using Alquileres.Infrastructuree.EntityFrameworkDatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Alquileres.Infrastructuree.Migrations
{
    [DbContext(typeof(AlquileresDBContext))]
    partial class AlquileresDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Alquileres.Domain.Owner", b =>
                {
                    b.Property<string>("IdOwner")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .HasColumnType("TEXT");

                    b.HasKey("IdOwner");

                    b.ToTable("Owners");
                });
#pragma warning restore 612, 618
        }
    }
}
